enum Action {
    RENDA,
    AJUDA_EXTERNA,
    TAXAR,
    CORRUPCAO,
    EXTORQUIR,
    ASSASSINAR,
    INVESTIGAR,
    GOLPE_ESTADO,
    TROCAR,
    TROCAR_PROPRIA_RELIGIAO,
    TROCAR_RELIGIAO_OUTRO,
    CONTESTAR,
    BLOQUEAR,
    CONTINUAR
}

export default Action;