export enum TutorialType {
    INTRODUCAO = "introducao",
    ASSASSINO = "assassino",
    CAPITAO = "capitao",
    CONDESSA = "condessa",
    DUQUE = "duque",
    EMBAIXADOR = "embaixador",
    INQUISIDOR = "inquisidor",
    RENDA = "renda",
    AJUDA_EXTERNA = "ajuda_externa",
    GOLPE_ESTADO = "golpe_estado",
    ASSASSINAR = "assassinar",
    EXTORQUIR = "extorquir",
    TAXAR = "taxar",
    TROCAR = "trocar",
    INVESTIGAR = "inventigar",
    BLOQUEAR = "bloquear",
    CONTESTAR = "contestar",
    CONTINUAR = "continuar",
    RELIGIAO = "religiao",
    CORRUPCAO = "corrupcao",
    DEVERES = "deveres"
}